version: '3'

services:
  orbis-training-project:
   build: .
   volumes:
     - ./:/app
   command: npm start
   working_dir: /app
   ports:
     - "1042:3030"
     - "35729:35729"
  test:
    depends_on: 
      - orbis-training-project
    image: node:10.10.0-slim
    networks: 
      - "orbistrainingproject_default"
    command: curl http://orbistrainingproject_orbis-training-project_1:3030
networks: 
  orbistrainingproject_default:
    external:
      name: orbistrainingproject_default